### ISSUE TITLE
Deleted posts appear as [DELETED]

### ISSUE THREAD

**Issue by paulstringer** [backchannel/BackchannelSDK-iOS#5]
When deleting posts from backchannel, they aren't removed from the feed but appear as [DELETED]. Is this by design or a bug? When using we're expecting these to simply disappear.

**Comment by khanlou** [comment]
This is intentional. We went with a Reddit-style deletion policy, where posts that are deleted will stay in place, so that it doesn't confuse users when posts disappear and the conversation stops making sense. This deletion policy isn't final, though, and I'm totally open to arguments on why it should change.

One possibility is that the whole thread could be removable, but messages would show up as "[Deleted]".

**Comment by paulstringer** [comment]
That answers it, sounds like a reasonable way to approach it. Works for me just wanted to understand it.
